(()=>{'use strict';
const $=id=>document.getElementById(id),KEY='nourish_v5';
const today=()=>{const d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')};
const plus=n=>{const d=new Date();d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)};
const seed={foods:[{name:'Lindahls Pro+ Lemon Cheesecake',kcal:150,protein:20,carbs:10,fat:3,unit:'pot'},{name:'Chicken breast',kcal:165,protein:31,carbs:0,fat:3.6,unit:'100g'},{name:'Veetee Sticky Rice',kcal:152,protein:3,carbs:33.1,fat:.8,unit:'100g'},{name:'Strawberries',kcal:32,protein:.7,carbs:7.7,fat:.3,unit:'100g'},{name:'Baby potatoes',kcal:77,protein:2,carbs:17,fat:.1,unit:'100g'},{name:'Greek yoghurt',kcal:73,protein:9.9,carbs:3.8,fat:2,unit:'100g'}],meals:[{name:'Honey Chilli Chicken',kcal:518,protein:42,carbs:50,fat:14,portions:1,ingredients:[{foodIndex:1,grams:150}]},{name:'Spicy Tomato Chicken Rigatoni',kcal:462,protein:36,carbs:55,fat:9,portions:1,ingredients:[{foodIndex:1,grams:120}]},{name:'Chicken & Roast Potatoes',kcal:574,protein:38,carbs:48,fat:20,portions:1,ingredients:[{foodIndex:1,grams:150},{foodIndex:4,grams:250}]}],inventory:[{name:'Strawberries',qty:'250g',date:plus(1)},{name:'Chicken breast',qty:'600g',date:plus(2)},{name:'Baby potatoes',qty:'1kg',date:plus(3)},{name:'Milk',qty:'1L',date:plus(12)}],logs:[],water:0};
let state;try{state=JSON.parse(localStorage.getItem(KEY))||seed}catch(e){state=seed}state={...seed,...state,foods:Array.isArray(state.foods)?state.foods:[],meals:Array.isArray(state.meals)?state.meals:[],inventory:Array.isArray(state.inventory)?state.inventory:[],logs:Array.isArray(state.logs)?state.logs:[],water:+state.water||0};
let currentProduct=null,currentMealIngredients=[];
const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const toast=t=>{const x=$('toast');if(!x)return;x.textContent=t;x.style.display='block';setTimeout(()=>x.style.display='none',2000)};
const open=id=>$(id)?.classList.add('open'),close=id=>$(id)?.classList.remove('open');
const days=d=>Math.ceil((new Date(d)-new Date(new Date().toDateString()))/86400000);
const parseG=q=>{const m=String(q||'').match(/([0-9]+(?:\.[0-9]+)?)\s*(kg|g)\b/i);return m?+m[1]*(m[2].toLowerCase()==='kg'?1000:1):null};
function render(){const logs=state.logs.filter(x=>x.date===today()),sum=k=>logs.reduce((a,x)=>a+(+x[k]||0),0),k=sum('kcal'),p=sum('protein'),c=sum('carbs'),f=sum('fat');$('kcal').textContent=Math.round(k);$('proteinText').textContent=Math.round(p)+' / 130g';$('carbsText').textContent=Math.round(c)+' / 200g';$('fatText').textContent=Math.round(f)+' / 65g';$('proteinBar').style.width=Math.min(100,p/130*100)+'%';$('carbsBar').style.width=Math.min(100,c/200*100)+'%';$('fatBar').style.width=Math.min(100,f/65*100)+'%';$('ring').style.setProperty('--prog',Math.min(100,k/1900*100)+'%');$('waterText').textContent=(state.water/1000).toFixed(1)+' / 2.0L';$('waterBar').style.width=Math.min(100,state.water/20)+'%';$('todayLog').innerHTML=logs.length?logs.map(x=>`<div class="item row"><b>🍽️ ${esc(x.name)}</b><b>${Math.round(x.kcal)} kcal</b></div>`).join(''):'<div class="item sub">Nothing logged yet.</div>';renderFoods();renderMeals();renderKitchen();renderIdeas()}
function renderFoods(){const q=($('foodSearch')?.value||'').toLowerCase();const a=state.foods.map((x,i)=>({x,i})).filter(o=>o.x.name.toLowerCase().includes(q));$('foodList').innerHTML=a.map(o=>`<div class="item row"><div><b>🍎 ${esc(o.x.name)}</b><div class="sub">${o.x.kcal} kcal / ${esc(o.x.unit||'100g')}</div></div><button class="btn small" data-add-food="${o.i}">＋</button></div>`).join('')||'<div class="item sub">No saved foods found.</div>'}
function renderMeals(){$('mealList').innerHTML=state.meals.map((m,i)=>`<div class="card"><div class="row"><div><b>🍽️ ${esc(m.name)}</b><div class="sub">${Math.round(m.kcal)} kcal · ${Math.round(m.protein||0)}g protein / portion</div></div><button class="btn small" data-log-meal="${i}">＋</button></div></div>`).join('')||'<div class="card sub">Create your first meal.</div>'}
function renderKitchen(){const inv=[...state.inventory].sort((a,b)=>days(a.date)-days(b.date)),soon=inv.filter(x=>days(x.date)<=3);$('stockCount').textContent=inv.length+' item'+(inv.length===1?'':'s');const card=x=>{const d=days(x.date),label=d<0?'Expired':d===0?'Today':d===1?'Tomorrow':'in '+d+' days',cls=d<=0?'expiry':d<=3?'soon':'sub';return `<div class="item row"><div><b>📦 ${esc(x.name)}</b><div class="sub">${esc(x.qty)}</div></div><span class="${cls}">${label}</span></div>`};$('kitchenSoon').innerHTML=soon.length?soon.map(card).join(''):'<div class="item sub">Nothing needs using urgently 🎉</div>';$('inventoryList').innerHTML=inv.length?inv.map(card).join(''):'<div class="item sub">Kitchen is empty.</div>';$('useSummary').textContent=soon.length?soon.length+' item(s) need attention':'Nothing urgent 🎉';$('useSoon').innerHTML=soon.slice(0,3).map(card).join('')}
function renderIdeas(){const ranked=state.meals.map((m,i)=>{let have=0,urgent=0;(m.ingredients||[]).forEach(x=>{const f=state.foods[x.foodIndex],it=f&&state.inventory.find(v=>v.name.toLowerCase()===f.name.toLowerCase());if(it){const g=parseG(it.qty),need=(+x.grams||0)/Math.max(1,+m.portions||1);if(g!=null&&g>=need)have++;if(days(it.date)<=3)urgent++}});return{m,i,have,urgent}}).filter(x=>x.have>0).sort((a,b)=>b.have-a.have||b.urgent-a.urgent).slice(0,4);$('ideasList').innerHTML=ranked.length?ranked.map((r,n)=>`<div class="idea"><div class="row"><div class="row"><span class="rank">${n+1}</span><div><b>${esc(r.m.name)}</b><div class="sub">${r.have} ingredient${r.have===1?'':'s'} available${r.urgent?' · 🔥 '+r.urgent+' expiring soon':''}</div></div></div><button class="btn small" data-log-meal="${r.i}">＋</button></div></div>`).join(''):'<div class="item sub">Add ingredients to Kitchen to get personalised meal ideas.</div>'}
function addFood(food){state.logs.push({date:today(),name:food.name,kcal:+food.kcal||0,protein:+food.protein||0,carbs:+food.carbs||0,fat:+food.fat||0});save();render();toast('Added to today ✓')}
function logMeal(meal){state.logs.push({date:today(),name:meal.name,kcal:meal.kcal,protein:meal.protein,carbs:meal.carbs||0,fat:meal.fat||0});const portions=Math.max(1,+meal.portions||1);(meal.ingredients||[]).forEach(i=>{const food=state.foods[i.foodIndex];if(!food)return;const item=state.inventory.find(x=>x.name.toLowerCase()===food.name.toLowerCase()),have=item&&parseG(item.qty),need=(+i.grams||0)/portions;if(!item||have==null||have<need)return;const rem=have-need;item.qty=Math.round(rem*10)/10+'g';if(rem<=0)state.inventory=state.inventory.filter(x=>x!==item)});save();render();toast('Meal logged ✓')}
function water(n){state.water+=n;save();render();toast('Water added 💧')}
function addIngredientRow(){if(!state.foods.length)return toast('Create a food first');const wrap=$('ingredientPicker'),idx=currentMealIngredients.length,div=document.createElement('div');div.className='ingredient';div.innerHTML=`<select>${state.foods.map((f,i)=>`<option value="${i}">${esc(f.name)}</option>`).join('')}</select><input type="number" min="1" value="100" placeholder="grams">`;wrap.appendChild(div);currentMealIngredients.push({foodIndex:0,grams:100});div.querySelector('select').onchange=e=>{currentMealIngredients[idx].foodIndex=+e.target.value;updateMealTotals()};div.querySelector('input').oninput=e=>{currentMealIngredients[idx].grams=+e.target.value||0;updateMealTotals()};updateMealTotals()}
function updateMealTotals(){let t={kcal:0,protein:0,carbs:0,fat:0};currentMealIngredients.forEach(i=>{const f=state.foods[i.foodIndex],z=(+i.grams||0)/100;if(f){t.kcal+=(f.kcal||0)*z;t.protein+=(f.protein||0)*z;t.carbs+=(f.carbs||0)*z;t.fat+=(f.fat||0)*z}});const portions=Math.max(1,+$('mport').value||1);$('mealTotals').innerHTML=`<b>Recipe totals</b><div class="sub">${Math.round(t.kcal)} kcal · ${Math.round(t.protein)}g protein · ${Math.round(t.carbs)}g carbs · ${Math.round(t.fat)}g fat</div><div style="margin-top:8px"><b>Per portion: ${Math.round(t.kcal/portions)} kcal · ${Math.round(t.protein/portions)}g protein</b></div>`;return t}
function saveMeal(){const name=$('mn').value.trim();if(!name)return toast('Add a meal name');if(!currentMealIngredients.length)return toast('Add at least one ingredient');const t=updateMealTotals(),p=Math.max(1,+$('mport').value||1);state.meals.unshift({name,kcal:t.kcal/p,protein:t.protein/p,carbs:t.carbs/p,fat:t.fat/p,portions:p,ingredients:currentMealIngredients.map(x=>({...x}))});save();currentMealIngredients=[];$('ingredientPicker').innerHTML='';close('mealModal');render();toast('Meal saved ✓')}
function saveFood(){const f={name:$('fn').value.trim(),kcal:+$('fk').value||0,protein:+$('fp').value||0,carbs:+$('fc').value||0,fat:+$('ff').value||0,unit:'100g'};if(!f.name)return toast('Add a name');state.foods.unshift(f);save();close('foodModal');render();toast('Food saved ✓')}
function saveInv(){const n=$('inName').value.trim(),q=$('inQty').value.trim(),d=$('inDate').value;if(!n||!q||!d)return toast('Complete all fields');state.inventory.push({name:n,qty:q,date:d});save();close('invModal');render();toast('Added to Kitchen ✓')}
async function scan(){open('scanModal');$('barcodeInput').value='';$('scanStatus').textContent='Starting camera…';try{window.nourishScanner=new Html5Qrcode('reader');await nourishScanner.start({facingMode:'environment'},{fps:10,qrbox:{width:280,height:120},formatsToSupport:[Html5QrcodeSupportedFormats.EAN_13,Html5QrcodeSupportedFormats.EAN_8,Html5QrcodeSupportedFormats.UPC_A,Html5QrcodeSupportedFormats.UPC_E]},code=>{lookup(code)});$('scanStatus').textContent='Camera ready — line up the barcode.'}catch(e){$('scanStatus').textContent='Camera unavailable. Enter the barcode below.'}}
async function stopScan(){if(window.nourishScanner){try{await nourishScanner.stop();nourishScanner.clear()}catch(e){}window.nourishScanner=null}$('barcodeInput').value='';close('scanModal')}
async function lookup(code){code=String(code||$('barcodeInput').value).replace(/\D/g,'');if(!code)return toast('Enter a barcode');$('scanStatus').textContent='Looking up product…';try{const r=await fetch('https://world.openfoodfacts.org/api/v2/product/'+encodeURIComponent(code)+'.json?fields=code,product_name,brands,nutriments,image_front_url'),d=await r.json();if(d.status!==1||!d.product?.product_name){$('scanStatus').textContent='Product not found.';return}const n=d.product.nutriments||{};currentProduct={name:d.product.product_name,brand:d.product.brands||'',kcal:+(n['energy-kcal_100g']||0),protein:+(n.proteins_100g||0),carbs:+(n.carbohydrates_100g||0),fat:+(n.fat_100g||0),unit:'100g',barcode:code,image:d.product.image_front_url||''};await stopScan();showProduct()}catch(e){$('scanStatus').textContent='Lookup failed. Check your connection and try again.'}}
function showProduct(){const p=currentProduct;$('productResult').innerHTML=`${p.image?`<img src="${esc(p.image)}" style="width:90px;height:90px;object-fit:contain;border-radius:14px;background:#f2f5f1">`:''}<h2>${esc(p.name)}</h2><div class="sub">${esc(p.brand)} · ${esc(p.barcode)}</div><div class="nutrition"><div class="nut"><b>${Math.round(p.kcal)}</b><span class="sub">kcal / 100g</span></div><div class="nut"><b>${p.protein}g</b><span class="sub">protein</span></div><div class="nut"><b>${p.carbs}g</b><span class="sub">carbs</span></div><div class="nut"><b>${p.fat}g</b><span class="sub">fat</span></div></div><button class="btn" style="width:100%;margin-top:12px" data-a="productDiary">＋ Add to diary</button><button class="btn alt" style="width:100%;margin-top:8px" data-a="productSave">Save food</button><button class="btn alt" style="width:100%;margin-top:8px" data-a="productKitchen">Save food + Kitchen</button>`;open('productModal')}
function saveProduct(){const i=state.foods.findIndex(f=>f.barcode===currentProduct.barcode);if(i>=0)state.foods[i]=currentProduct;else state.foods.unshift(currentProduct);save();render();toast('Food saved ✓')}
function confirmKitchen(){const q=$('expiryQty').value.trim(),date=$('expiryDate').value;if(!q||!date)return toast('Add quantity and use-by date');state.inventory.push({name:currentProduct.name,qty:q,date,barcode:currentProduct.barcode});save();close('expiryModal');render();toast('Saved to Kitchen ✓')}
document.addEventListener('click',e=>{const b=e.target.closest('[data-nav],[data-modal],[data-close],[data-a],[data-add-food],[data-log-meal]');if(!b)return;if(b.dataset.nav){document.querySelectorAll('.screen').forEach(x=>x.classList.toggle('active',x.id===b.dataset.nav));document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x.dataset.nav===b.dataset.nav));render()}if(b.dataset.modal){if(b.dataset.modal==='mealModal'){currentMealIngredients=[];$('ingredientPicker').innerHTML='';updateMealTotals()}open(b.dataset.modal)}if(b.dataset.close)close(b.dataset.close);if(b.dataset.addFood!==undefined){const f=state.foods[+b.dataset.addFood];if(f)addFood(f)}if(b.dataset.logMeal!==undefined){const m=state.meals[+b.dataset.logMeal];if(m)logMeal(m)}switch(b.dataset.a){case'water':water(+b.dataset.n);break;case'scan':scan();break;case'lookup':lookup();break;case'addIngredient':addIngredientRow();break;case'saveMeal':saveMeal();break;case'saveFood':saveFood();break;case'saveInv':saveInv();break;case'productDiary':addFood(currentProduct);close('productModal');break;case'productSave':saveProduct();close('productModal');break;case'productKitchen':saveProduct();close('productModal');$('expiryProduct').innerHTML=`<b>${esc(currentProduct.name)}</b><div class="sub">${currentProduct.kcal} kcal / 100g</div>`;$('expiryQty').value='';$('expiryDate').value='';open('expiryModal');break;case'confirmKitchen':confirmKitchen();break}});
$('foodSearch')?.addEventListener('input',renderFoods);$('mport')?.addEventListener('input',updateMealTotals);render();save();
})();