(()=>{'use strict';
const KEY='nourish_v5';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const today=()=>{const d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')};
const days=d=>Math.ceil((new Date(d)-new Date(new Date().toDateString()))/86400000);
function load(){try{return JSON.parse(localStorage.getItem(KEY))||{}}catch(e){return {}}}
function save(s){localStorage.setItem(KEY,JSON.stringify(s))}
function renderUseFirst(){const s=load(),inv=Array.isArray(s.inventory)?s.inventory:[],soon=inv.filter(x=>days(x.date)<=3).sort((a,b)=>days(a.date)-days(b.date)).slice(0,3),el=document.getElementById('useSoon');if(!el)return;const html=soon.length?soon.map(x=>{const d=days(x.date),label=d<0?'Expired':d===0?'Today':d===1?'Tomorrow':'in '+d+' days';return `<div class="item row"><div><b>📦 ${esc(x.name)}</b><div class="sub">${esc(x.qty)}</div></div><span class="${d<=0?'expiry':'soon'}">${label}</span></div>`}).join(''):'<div class="item sub">Nothing needs using urgently 🎉</div>';el.innerHTML=html}
function logMealWithNotice(index){const s=load(),meals=Array.isArray(s.meals)?s.meals:[],meal=meals[index];if(!meal)return;const foods=Array.isArray(s.foods)?s.foods:[],inv=Array.isArray(s.inventory)?s.inventory:[],before=inv.map(x=>({...x}));const portions=Math.max(1,+meal.portions||1);(meal.ingredients||[]).forEach(ing=>{const f=foods[ing.foodIndex];if(!f)return;const it=inv.find(x=>String(x.name).toLowerCase()===String(f.name).toLowerCase());if(!it)return;const m=String(it.qty||'').match(/([0-9]+(?:\.[0-9]+)?)\s*(kg|g)\b/i);if(!m)return;const have=+m[1]*(m[2].toLowerCase()==='kg'?1000:1),need=(+ing.grams||0)/portions,remaining=have-need;if(remaining<=0){const p=inv.indexOf(it);if(p>=0)inv.splice(p,1)}else it.qty=Math.round(remaining*10)/10+'g'});s.inventory=inv;s.logs=Array.isArray(s.logs)?s.logs:[];s.logs.push({date:today(),name:meal.name,kcal:+meal.kcal||0,protein:+meal.protein||0,carbs:+meal.carbs||0,fat:+meal.fat||0});save(s);const changes=[];before.forEach(old=>{const now=inv.find(x=>String(x.name).toLowerCase()===String(old.name).toLowerCase());if(!now)changes.push(old.name+' depleted');else if(now.qty!==old.qty)changes.push(old.name+' '+old.qty+' → '+now.qty)});const expiring=inv.filter(x=>days(x.date)<=3).sort((a,b)=>days(a.date)-days(b.date)).slice(0,2);const notice=document.getElementById('toast');if(notice){notice.innerHTML='<b>🍽️ '+esc(meal.name)+' logged</b>'+(changes.length?'<div class="sub" style="margin-top:4px">'+changes.map(esc).join(' · ')+'</div>':'')+(expiring.length?'<div class="sub" style="margin-top:4px">🔥 Still use soon: '+expiring.map(x=>esc(x.name)).join(', ')+'</div>':'');notice.style.display='block';setTimeout(()=>notice.style.display='none',3500)}renderUseFirst();window.dispatchEvent(new Event('nourish:data-changed'))}
function patch(){document.addEventListener('click',e=>{const b=e.target.closest('[data-log-meal]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();logMealWithNotice(+b.dataset.logMeal)},true);renderUseFirst()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',patch);else patch();
})();
