(()=>{'use strict';
const KEY='nourish_v5';
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let scanner=null,current=null;
function load(){try{return JSON.parse(localStorage.getItem(KEY))||{}}catch(e){return {}}}
function save(s){localStorage.setItem(KEY,JSON.stringify(s));}
function modal(){let m=$('kitchenScanModal');if(m)return m;m=document.createElement('div');m.id='kitchenScanModal';m.className='modal';m.innerHTML='<div class="sheet"><div class="row"><b>📷 Scan into Kitchen</b><button class="close" id="kitchenScanClose">×</button></div><div id="kitchenReader"></div><div id="kitchenScanStatus" class="status">Allow camera access, then line up the barcode.</div><input id="kitchenBarcode" inputmode="numeric" autocomplete="off" placeholder="Or enter barcode manually"><button class="btn" style="width:100%" id="kitchenLookup">Look up product</button></div></div>';document.body.appendChild(m);$('kitchenScanClose').onclick=closeScan;$('kitchenLookup').onclick=()=>lookup($('kitchenBarcode').value);return m}
function openScan(){const m=modal();m.classList.add('open');$('kitchenBarcode').value='';$('kitchenScanStatus').textContent='Starting camera…';setTimeout(startCamera,50)}
async function startCamera(){try{if(!window.Html5Qrcode){$('kitchenScanStatus').textContent='Camera scanner unavailable. Enter the barcode below.';return}scanner=new Html5Qrcode('kitchenReader');await scanner.start({facingMode:'environment'},{fps:10,qrbox:{width:280,height:120},formatsToSupport:[Html5QrcodeSupportedFormats.EAN_13,Html5QrcodeSupportedFormats.EAN_8,Html5QrcodeSupportedFormats.UPC_A,Html5QrcodeSupportedFormats.UPC_E]},code=>{$('kitchenBarcode').value=code;lookup(code)});$('kitchenScanStatus').textContent='Camera ready — line up the barcode.'}catch(e){$('kitchenScanStatus').textContent='Camera unavailable. Enter the barcode below.'}}
async function closeScan(){if(scanner){try{await scanner.stop();scanner.clear()}catch(e){}scanner=null}$('kitchenReader').innerHTML='';$('kitchenScanModal')?.classList.remove('open')}
async function lookup(code){code=String(code||'').replace(/\D/g,'');if(!code)return;$('kitchenScanStatus').textContent='Looking up product…';try{const r=await fetch('https://world.openfoodfacts.org/api/v2/product/'+encodeURIComponent(code)+'.json?fields=code,product_name,brands,nutriments,product_quantity,serving_size,image_front_url');const d=await r.json();if(d.status!==1||!d.product?.product_name){$('kitchenScanStatus').textContent='Product not found. Try entering the barcode manually.';return}const n=d.product.nutriments||{};current={name:d.product.product_name,brand:d.product.brands||'',barcode:code,kcal:+(n['energy-kcal_100g']||0),protein:+(n.proteins_100g||0),carbs:+(n.carbohydrates_100g||0),fat:+(n.fat_100g||0),image:d.product.image_front_url||'',quantity:d.product.product_quantity||''};await closeScan();openConfirm()}catch(e){$('kitchenScanStatus').textContent='Lookup failed. Check your connection and try again.'}}
function openConfirm(){let m=$('kitchenConfirmModal');if(!m){m=document.createElement('div');m.id='kitchenConfirmModal';m.className='modal';m.innerHTML='<div class="sheet"><div class="row"><h2>Add to Kitchen</h2><button class="close" id="kitchenConfirmClose">×</button></div><div id="kitchenProduct" class="item"></div><label>Quantity</label><input id="kitchenQty" placeholder="e.g. 500g or 1 pack"><label>Use-by date</label><input id="kitchenDate" type="date"><button class="btn" style="width:100%" id="kitchenSave">Save to Kitchen</button></div></div>';document.body.appendChild(m);$('kitchenConfirmClose').onclick=()=>m.classList.remove('open');$('kitchenSave').onclick=saveKitchen}const p=current;$('kitchenProduct').innerHTML=(p.image?'<img src="'+esc(p.image)+'" style="width:70px;height:70px;object-fit:contain;border-radius:12px">':'')+'<div><b>'+esc(p.name)+'</b><div class="sub">'+esc(p.brand)+' · '+esc(p.barcode)+'</div><div class="sub">'+p.kcal+' kcal / 100g</div></div>';$('kitchenQty').value=p.quantity||'';$('kitchenDate').value='';m.classList.add('open')}
function saveKitchen(){const q=$('kitchenQty').value.trim(),date=$('kitchenDate').value;if(!q||!date)return alert('Add quantity and use-by date');const s=load();s.inventory=Array.isArray(s.inventory)?s.inventory:[];s.inventory.push({name:current.name,qty:q,date,barcode:current.barcode,kcal:current.kcal,protein:current.protein,carbs:current.carbs,fat:current.fat});save(s);$('kitchenConfirmModal').classList.remove('open');if(typeof window.nourishStore?.emit==='function')window.nourishStore.emit('change');if(typeof window.render==='function')window.render();else location.reload()}
function augmentIngredientPicker(){const picker=$('ingredientPicker');if(!picker)return;const selects=picker.querySelectorAll('select[data-ing-food]');if(!selects.length)return;const s=load(),inv=Array.isArray(s.inventory)?s.inventory:[],foods=Array.isArray(s.foods)?s.foods:[];selects.forEach(sel=>{const existing=new Set([...sel.options].map(o=>o.value));inv.forEach(item=>{const idx=foods.findIndex(f=>String(f.name).toLowerCase()===String(item.name).toLowerCase());if(idx>=0&&!existing.has(String(idx))){const o=document.createElement('option');o.value=String(idx);o.textContent='📦 '+item.name+' (Kitchen)';sel.appendChild(o);}})});}
document.addEventListener('click',e=>{if(e.target.closest('[data-a="scanKitchen"]')){e.preventDefault();openScan()}else if(e.target.closest('[data-a="addIngredient"]')){setTimeout(augmentIngredientPicker,0)}});
})();