(()=>{'use strict';
const KEY='nourish_v5',SET='nourish_settings',LIST='nourish_shopping_v1';
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const read=()=>{try{return JSON.parse(localStorage.getItem(KEY))||{}}catch(e){return{}}};
const goals=()=>{try{return {...{kcal:1900,protein:130,carbs:200,fat:65},...(JSON.parse(localStorage.getItem(SET))||{})}}catch(e){return{kcal:1900,protein:130,carbs:200,fat:65}}};
const dateKey=d=>d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');
const daysLeft=d=>Math.ceil((new Date(d)-new Date(new Date().toDateString()))/86400000);
const grams=q=>{const m=String(q||'').match(/([0-9]+(?:\\.[0-9]+)?)\\s*(kg|g)\\b/i);return m?+m[1]*(m[2].toLowerCase()==='kg'?1000:1):null};
const num=(v)=>Math.round(Number(v)||0);
const state=()=>{const s=read();s.foods=Array.isArray(s.foods)?s.foods:[];s.meals=Array.isArray(s.meals)?s.meals:[];s.inventory=Array.isArray(s.inventory)?s.inventory:[];s.logs=Array.isArray(s.logs)?s.logs:[];return s};
function addStyles(){if($('plannerStyles'))return;const s=document.createElement('style');s.id='plannerStyles';s.textContent=`
.planner-tools{margin-top:14px}.planner-card{background:var(--card);border:1px solid var(--line);border-radius:22px;padding:16px;margin:12px 0;box-shadow:var(--shadow)}.planner-card h2{font-size:19px;letter-spacing:-.4px;margin:0 0 5px}.planner-card h3{font-size:15px;margin:0}.planner-sub{font-size:12px;color:var(--muted);line-height:1.45}.planner-row{display:flex;align-items:center;justify-content:space-between;gap:10px}.planner-row+.planner-row{margin-top:10px}.planner-pill{background:#eef6df;color:#527600;border-radius:999px;padding:5px 9px;font-size:11px;font-weight:800}.planner-item{border-top:1px solid var(--line);padding:12px 0}.planner-item:first-of-type{margin-top:6px}.planner-item p{margin:4px 0}.planner-mini{font-size:12px;color:var(--muted)}.planner-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}.planner-actions .btn{flex:1}.planner-input{width:76px;padding:9px;border:1px solid var(--line);border-radius:12px;background:var(--bg);color:var(--ink)}.planner-check{display:flex;align-items:center;gap:9px;padding:10px 0;border-bottom:1px solid var(--line);font-size:13px}.planner-check input{accent-color:var(--g);width:18px;height:18px}.planner-check.done span{text-decoration:line-through;color:var(--muted)}.planner-metrics{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px;margin-top:12px}.planner-metric{background:var(--bg);border-radius:15px;padding:12px}.planner-metric b{font-size:22px;display:block}.planner-bar{height:7px;border-radius:9px;background:var(--line);overflow:hidden;margin-top:6px}.planner-bar span{height:100%;display:block;background:var(--g);border-radius:9px}.planner-note{background:#fff4ed;border-radius:13px;padding:10px;color:#8e4c37;font-size:12px;line-height:1.45;margin-top:10px}.planner-empty{padding:12px 0;color:var(--muted);font-size:13px}.planner-tools .btn.small{white-space:nowrap}
`;document.head.appendChild(s)}
function ensureUI(){const ideas=$('ideas');if(!ideas||$('nourishPlannerTools'))return;const root=document.createElement('div');root.id='nourishPlannerTools';root.className='planner-tools';root.innerHTML=`
<section class="planner-card" id="dailyPlanner"><div class="planner-row"><div><h2>🧠 Your daily food planner</h2><div class="planner-sub">Suggestions based on today's remaining targets and what's in your kitchen.</div></div><span class="planner-pill">SMART PICKS</span></div><div id="dailyPlannerBody" class="planner-empty">Loading your suggestions…</div></section>
<section class="planner-card" id="useSoonRecipes"><div class="planner-row"><div><h2>🔥 Rescue your ingredients</h2><div class="planner-sub">Recipe ideas that prioritise food nearing its use-by date.</div></div></div><div id="useSoonRecipeBody" class="planner-empty"></div></section>
<section class="planner-card" id="weeklyTrends"><div><h2>📈 Weekly nutrition trends</h2><div class="planner-sub">Your last seven days, based on days with food logged.</div></div><div id="weeklyTrendBody" class="planner-empty"></div></section>
<section class="planner-card" id="recipeScaler"><div><h2>👩‍🍳 Recipe builder & portion scaler</h2><div class="planner-sub">Scale saved recipes up or down and see ingredient amounts and nutrition totals.</div></div><div id="recipeScalerBody" class="planner-empty"></div></section>
<section class="planner-card" id="shoppingPlanner"><div><h2>🛒 Shopping list builder</h2><div class="planner-sub">Choose saved recipes to combine ingredients, subtract what you already have, and build a checklist.</div></div><div id="shoppingPlannerBody" class="planner-empty"></div></section>`;
ideas.appendChild(root);renderAll()}
function todayLogs(s){const key=dateKey(new Date());return s.logs.filter(x=>x.date===key)}
function totals(items){return items.reduce((a,x)=>{['kcal','protein','carbs','fat'].forEach(k=>a[k]+=Number(x[k])||0);return a},{kcal:0,protein:0,carbs:0,fat:0})}
function dailyPlanner(s){const g=goals(),t=totals(todayLogs(s)),left={kcal:g.kcal-t.kcal,protein:g.protein-t.protein,carbs:g.carbs-t.carbs,fat:g.fat-t.fat};const candidates=s.meals.map(m=>({m,score:(left.kcal>0&&m.kcal<=left.kcal?30:0)+(left.protein>0&&m.protein<=left.protein?Math.min(35,(m.protein/Math.max(1,left.protein))*35):0)+(left.kcal>0?Math.max(0,20-Math.abs(left.kcal-m.kcal)/Math.max(1,left.kcal)*20):0)})).filter(x=>left.kcal>0&&x.m.kcal<=left.kcal*1.12).sort((a,b)=>b.score-a.score).slice(0,3);
const leftText=(v,u)=>Math.abs(num(v)).toLocaleString()+' '+u+(v<0?' over':' left');
let html='<div class="planner-metrics"><div class="planner-metric"><span class="planner-sub">Calories</span><b>'+leftText(left.kcal,'kcal')+'</b><div class="planner-bar"><span style="width:'+Math.min(100,t.kcal/Math.max(1,g.kcal)*100)+'%"></span></div></div><div class="planner-metric"><span class="planner-sub">Protein</span><b>'+leftText(left.protein,'g')+'</b><div class="planner-bar"><span style="width:'+Math.min(100,t.protein/Math.max(1,g.protein)*100)+'%"></span></div></div></div>';
if(left.kcal<=0)html+='<div class="planner-note">You have reached or exceeded today’s calorie target. Suggestions below are simply options, not pressure to eat less.</div>';
if(candidates.length)html+='<div class="planner-sub" style="margin-top:12px">Saved meals that fit your remaining allowance:</div>'+candidates.map(({m})=>'<div class="planner-item"><div class="planner-row"><div><h3>'+esc(m.name)+'</h3><p class="planner-mini">'+num(m.kcal)+' kcal · '+num(m.protein)+'g protein per portion</p></div><button class="btn small" data-planner-log="'+esc(m.id)+'">＋ Log</button></div></div>').join('');
else html+='<div class="planner-empty">'+(s.meals.length?'No saved meals fit the remaining calories closely. Try scaling a recipe below or create another meal.':'Create a saved meal to get personalised daily suggestions.')+'</div>';
$('dailyPlannerBody').innerHTML=html}
function useSoonRecipes(s){const soon=s.inventory.filter(i=>i.date&&daysLeft(i.date)<=3);if(!soon.length){$('useSoonRecipeBody').innerHTML='<div class="planner-empty">Nothing urgent in your kitchen right now. Add use-by dates to get smarter suggestions.</div>';return}
const urgentNames=soon.map(i=>i.name.toLowerCase());const ranked=s.meals.map(m=>{const ingredients=m.ingredients||[];let urgent=0,available=0,missing=[];ingredients.forEach(ing=>{const f=s.foods.find(x=>x.id===ing.foodId)||s.foods[ing.foodIndex];if(!f)return;const inv=s.inventory.find(i=>i.name.toLowerCase()===f.name.toLowerCase());if(inv){available++;if(urgentNames.includes(inv.name.toLowerCase()))urgent++}else missing.push(f.name)});return{m,urgent,available,missing,total:ingredients.length,score:urgent*100+available*10-missing.length*4}}).filter(x=>x.urgent>0).sort((a,b)=>b.score-a.score).slice(0,4);
$('useSoonRecipeBody').innerHTML=ranked.length?ranked.map(x=>'<div class="planner-item"><div class="planner-row"><div><h3>'+esc(x.m.name)+'</h3><p class="planner-mini">Uses '+x.urgent+' soon-to-expire ingredient'+(x.urgent===1?'':'s')+' · '+x.available+'/'+x.total+' ingredients in Kitchen</p>'+(x.missing.length?'<p class="planner-mini">Still needed: '+x.missing.map(esc).join(', ')+'</p>':'<p class="planner-mini">You appear to have everything in stock ✓</p>')+'</div><button class="btn small" data-planner-recipe="'+esc(x.m.id)+'">View recipe</button></div></div>').join(''):'<div class="planner-empty">Your soon-to-expire items are listed below, but no saved recipes currently use them. Add ingredient lists to your meals to unlock tailored suggestions.</div>'}
function weeklyTrends(s){const g=goals(),base=new Date(),days=[];for(let i=6;i>=0;i--){const d=new Date(base);d.setHours(0,0,0,0);d.setDate(d.getDate()-i);const key=dateKey(d),items=s.logs.filter(x=>x.date===key),t=totals(items);days.push({key,label:new Intl.DateTimeFormat('en-GB',{weekday:'short'}).format(d),...t,count:items.length})}const active=days.filter(d=>d.count),avg=k=>active.length?active.reduce((a,d)=>a+d[k],0)/active.length:0,within=active.filter(d=>d.kcal<=g.kcal).length,protein=active.filter(d=>d.protein>=g.protein).length;
$('weeklyTrendBody').innerHTML='<div class="planner-metrics"><div class="planner-metric"><span class="planner-sub">Avg calories / logged day</span><b>'+num(avg('kcal')).toLocaleString()+'</b><span class="planner-sub">kcal</span></div><div class="planner-metric"><span class="planner-sub">Avg protein / logged day</span><b>'+num(avg('protein'))+'g</b><span class="planner-sub">protein</span></div><div class="planner-metric"><span class="planner-sub">Days within calorie goal</span><b>'+within+'/'+active.length+'</b><span class="planner-sub">logged days</span></div><div class="planner-metric"><span class="planner-sub">Protein goal reached</span><b>'+protein+'/'+active.length+'</b><span class="planner-sub">logged days</span></div></div><div style="margin-top:14px">'+days.map(d=>'<div style="margin:9px 0"><div class="planner-row"><span class="planner-mini">'+d.label+' '+d.key.slice(8)+'</span><b class="planner-mini">'+(d.count?num(d.kcal)+' kcal':'No log')+'</b></div><div class="planner-bar"><span style="width:'+Math.min(100,d.kcal/Math.max(1,g.kcal)*100)+'%;opacity:'+(d.count?1:.2)+'"></span></div></div>').join('')+'</div><div class="planner-sub" style="margin-top:8px">Averages use '+active.length+' day'+(active.length===1?'':'s')+' with food logged; blank days are not counted as zero.</div>'}
function scaler(s){if(!s.meals.length){$('recipeScalerBody').innerHTML='<div class="planner-empty">Save a recipe in Meals first, then you can scale its portions here.</div>';return}
$('recipeScalerBody').innerHTML=s.meals.map(m=>'<div class="planner-item" data-scale-card="'+esc(m.id)+'"><div class="planner-row"><div><h3>'+esc(m.name)+'</h3><p class="planner-mini">'+num(m.kcal)+' kcal · '+num(m.protein)+'g protein per portion</p></div><label class="planner-mini">Servings <input class="planner-input" type="number" min="1" max="50" value="'+Math.max(1,num(m.portions)||1)+'" data-scale="'+esc(m.id)+'"></label></div><div class="planner-mini" data-scale-result="'+esc(m.id)+'"></div><button class="btn alt small" style="margin-top:8px" data-planner-shopping="'+esc(m.id)+'">Add ingredients to shopping list</button></div>').join('');
s.meals.forEach(m=>scaleResult(m))}
function scaleResult(m){const el=document.querySelector('[data-scale-result="'+CSS.escape(m.id)+'"]'),input=document.querySelector('[data-scale="'+CSS.escape(m.id)+'"]');if(!el||!input)return;const n=Math.max(1,Math.min(50,+input.value||1));const ingredients=(m.ingredients||[]).map(ing=>{const f=read().foods.find(x=>x.id===ing.foodId)||read().foods[ing.foodIndex];return f?esc(f.name)+': '+num((+ing.grams||0)/Math.max(1,+m.portions||1)*n)+'g':''}).filter(Boolean);el.innerHTML='<p style="margin:9px 0 3px">Total for '+n+' serving'+(n===1?'':'s')+': <b>'+num((+m.kcal||0)*n)+' kcal · '+num((+m.protein||0)*n)+'g protein</b></p>'+(ingredients.length?'<p>Ingredients: '+ingredients.join(' · ')+'</p>':'<p>Add ingredients to this recipe to see scaled quantities.</p>')}
function getList(){try{return JSON.parse(localStorage.getItem(LIST)||'[]')}catch(e){return[]}}
function saveList(list){localStorage.setItem(LIST,JSON.stringify(list))}
function shopping(s){const list=getList();const checked=list.filter(x=>x.done).length;
$('shoppingPlannerBody').innerHTML='<div class="planner-sub" style="margin-top:10px">Select recipes below. Nourish combines duplicate ingredients and subtracts measurable quantities already in Kitchen.</div><div id="shoppingRecipeChoices">'+s.meals.map(m=>'<label class="planner-check"><input type="checkbox" data-shop-recipe="'+esc(m.id)+'" '+(list.some(x=>x.recipeId===m.id)?'checked':'')+'><span>'+esc(m.name)+'</span></label>').join('')+'</div><div class="planner-actions"><button class="btn" id="generateShopping">Build shopping list</button><button class="btn alt" id="clearShopping">Clear list</button></div><div id="shoppingListItems" style="margin-top:8px">'+(list.length?list.map((x,i)=>'<label class="planner-check '+(x.done?'done':'')+'"><input type="checkbox" data-shop-done="'+i+'" '+(x.done?'checked':'')+'><span>'+esc(x.name)+' <span class="planner-mini">— '+esc(x.qty)+'</span></span></label>').join(''):'<div class="planner-empty">Your shopping list will appear here.</div>')+'</div><div class="planner-sub" style="margin-top:8px">'+checked+' of '+list.length+' items ticked off.</div>';
}
function buildShopping(){const s=state(),chosen=[...document.querySelectorAll('[data-shop-recipe]:checked')].map(x=>s.meals.find(m=>m.id===x.dataset.shopRecipe)).filter(Boolean);if(!chosen.length){const root=$('shoppingListItems');if(root)root.innerHTML='<div class="planner-empty">Select at least one recipe first.</div>';return}
const needs={};chosen.forEach(m=>(m.ingredients||[]).forEach(ing=>{const f=s.foods.find(x=>x.id===ing.foodId)||s.foods[ing.foodIndex];if(!f)return;const key=f.name.toLowerCase(),amount=(+ing.grams||0)/Math.max(1,+m.portions||1);if(!needs[key])needs[key]={name:f.name,grams:0,unmeasured:false,recipeId:m.id};needs[key].grams+=amount}));
const old=getList(),list=Object.values(needs).map(n=>{const inv=s.inventory.filter(i=>i.name.toLowerCase()===n.name.toLowerCase()).reduce((a,i)=>a+(grams(i.qty)||0),0),remaining=Math.max(0,n.grams-inv),prev=old.find(x=>x.name.toLowerCase()===n.name.toLowerCase());return{name:n.name,qty:remaining?num(remaining)+'g':(inv?'Already in Kitchen':'Check quantity'),done:prev?.done||false,grams:remaining,recipeId:n.recipeId}}).filter(x=>x.grams>0);saveList(list);shopping(s)}
function refresh(){if(!$('nourishPlannerTools'))return;const s=state();dailyPlanner(s);useSoonRecipes(s);weeklyTrends(s);scaler(s);shopping(s)}
function renderAll(){addStyles();refresh()}
document.addEventListener('click',e=>{const log=e.target.closest('[data-planner-log]');if(log){const s=state(),m=s.meals.find(x=>x.id===log.dataset.plannerLog);if(m&&window.NourishQueueFoodLog){window.NourishQueueFoodLog({name:m.name,kcal:m.kcal,protein:m.protein,carbs:m.carbs,fat:m.fat});return}return}
const view=e.target.closest('[data-planner-recipe]');if(view){const card=document.querySelector('[data-scale-card="'+CSS.escape(view.dataset.plannerRecipe)+'"]');if(card){card.scrollIntoView({behavior:'smooth',block:'center'});card.style.outline='2px solid var(--g)';setTimeout(()=>card.style.outline='',1200)}return}
const shop=e.target.closest('[data-planner-shopping]');if(shop){document.querySelectorAll('[data-shop-recipe]').forEach(x=>{if(x.dataset.shopRecipe===shop.dataset.plannerShopping)x.checked=true});buildShopping();return}
if(e.target.closest('#generateShopping')){buildShopping();return}
if(e.target.closest('#clearShopping')){saveList([]);shopping(state());return}
const done=e.target.closest('[data-shop-done]');if(done){const list=getList(),i=+done.dataset.shopDone;if(list[i])list[i].done=done.checked;saveList(list);shopping(state());return}
});
document.addEventListener('input',e=>{const input=e.target.closest('[data-scale]');if(input){const m=state().meals.find(x=>x.id===input.dataset.scale);if(m)scaleResult(m)}});
window.addEventListener('nourish:change',()=>{if($('nourishPlannerTools'))setTimeout(refresh,0)});
document.addEventListener('DOMContentLoaded',()=>{ensureUI();setTimeout(ensureUI,350);setTimeout(ensureUI,1000)});
setTimeout(ensureUI,0);
})();