(()=>{'use strict';
const KEY='nourish_v5';
const restaurants=[
{id:'mcdonalds',name:"McDonald's",emoji:'🍔',items:[{name:'Big Mac®',kcal:509,protein:27,carbs:41,fat:25},{name:'Double Big Mac®',kcal:684},{name:'McCrispy® Deluxe',kcal:601},{name:'Chilli Double Cheeseburger',kcal:440},{name:'Cheesy Garlic Bread Dippers',kcal:214}]},
{id:'nandos',name:"Nando's",emoji:'🍗',items:[{name:'The Big Caesar',kcal:649},{name:'Sol Bowl',kcal:583},{name:'Hearty Bowl',kcal:432}]}
];
const $=id=>document.getElementById(id);const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function mount(){const food=$('food');if(!food||$('eatOutBtn'))return;const grid=food.querySelector('.grid');if(!grid)return;const b=document.createElement('button');b.id='eatOutBtn';b.className='btn alt';b.style.cssText='grid-column:1/-1;width:100%;margin-top:8px';b.textContent='🍴 Eating out';b.addEventListener('click',openRestaurant);grid.appendChild(b)}
function openRestaurant(){let modal=$('restaurantModal');if(!modal){modal=document.createElement('div');modal.id='restaurantModal';modal.className='modal';modal.innerHTML='<div class="sheet"><div class="row"><h2>🍴 Eating out</h2><button class="close" id="restaurantClose">×</button></div><div id="restaurantBody"></div></div>';document.body.appendChild(modal);$('restaurantClose').onclick=()=>modal.classList.remove('open')}renderChains();modal.classList.add('open')}
function renderChains(){const body=$('restaurantBody');body.innerHTML='<div class="sub" style="margin-bottom:10px">UK menu nutrition · choose a restaurant</div><div class="grid">'+restaurants.map(r=>`<button class="btn alt" data-r="${r.id}">${r.emoji} ${esc(r.name)}</button>`).join('')+'</div><div id="restaurantItems"></div>';body.querySelectorAll('[data-r]').forEach(b=>b.onclick=()=>renderItems(b.dataset.r))}
function renderItems(id){const r=restaurants.find(x=>x.id===id);if(!r)return;const wrap=$('restaurantItems');const draw=()=>{const term=($('restaurantSearch')?.value||'').toLowerCase();const items=r.items.filter(x=>x.name.toLowerCase().includes(term));wrap.innerHTML='<input id="restaurantSearch" placeholder="🔍 Search '+esc(r.name)+' menu"><div class="card"><div class="row"><b>'+r.emoji+' '+esc(r.name)+'</b><span class="sub">'+items.length+' items</span></div>'+items.map((x,i)=>`<div class="item row"><div><b>${esc(x.name)}</b><div class="sub">${x.kcal} kcal${x.protein!=null?' · '+x.protein+'g protein':''}${x.carbs!=null?' · '+x.carbs+'g carbs':''}${x.fat!=null?' · '+x.fat+'g fat':''}</div><div class="sub">UK menu · nutrition can change</div></div><button class="btn small" data-add-restaurant="${i}">＋</button></div>`).join('')+'</div>';wrap.querySelector('#restaurantSearch').oninput=draw;wrap.querySelectorAll('[data-add-restaurant]').forEach(b=>b.onclick=()=>addToDiary(r,items[+b.dataset.addRestaurant]))};draw()}
function addToDiary(r,item){let s={};try{s=JSON.parse(localStorage.getItem(KEY))||{}}catch(e){}s.logs=Array.isArray(s.logs)?s.logs:[];const d=new Date();const date=d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');s.logs.push({date,name:r.name+' — '+item.name,kcal:item.kcal,protein:item.protein||0,carbs:item.carbs||0,fat:item.fat||0,source:'restaurant'});localStorage.setItem(KEY,JSON.stringify(s));$('restaurantModal').classList.remove('open');document.querySelector('[data-nav="today"]')?.click();const t=$('toast');if(t){t.textContent=item.name+' added to today ✓';t.style.display='block';setTimeout(()=>t.style.display='none',2000)}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount);else mount();setTimeout(mount,1000);setTimeout(mount,3000);
})();