(()=>{'use strict';
const KEY='nourish_v5';
const restaurants=[
{id:'mcdonalds',name:"McDonald's",emoji:'🍔',items:[{name:'Big Mac®',kcal:509,protein:27,carbs:41,fat:25},{name:'Double Big Mac®',kcal:684},{name:'McCrispy® Deluxe',kcal:601},{name:'Chilli Double Cheeseburger',kcal:440},{name:'Cheesy Garlic Bread Dippers',kcal:214}]},
{id:'nandos',name:"Nando's",emoji:'🍗',items:[{name:'The Big Caesar',kcal:649},{name:'Sol Bowl',kcal:583},{name:'Hearty Bowl',kcal:432}]}
];
const $=id=>document.getElementById(id);const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function mount(){const food=$('food');if(!food||$('eatOutBtn'))return;const grid=food.querySelector('.grid');if(!grid)return;const b=document.createElement('button');b.id='eatOutBtn';b.className='btn alt';b.style.cssText='grid-column:1/-1;width:100%;margin-top:8px';b.textContent='🍴 Eating out';b.addEventListener('click',openRestaurant);grid.appendChild(b)}
function openRestaurant(){let modal=$('restaurantModal');if(!modal){modal=document.createElement('div');modal.id='restaurantModal';modal.className='modal';modal.innerHTML='<div class="sheet restaurant-sheet"><div class="row"><h2>🍴 Eating out</h2><button class="close" id="restaurantClose">×</button></div><div id="restaurantBody" class="restaurant-results"></div></div>';document.body.appendChild(modal);$('restaurantClose').onclick=()=>modal.classList.remove('open')}renderChains();modal.classList.add('open')}
function renderChains(){const body=$('restaurantBody');body.innerHTML='<div class="sub" style="margin-bottom:10px">UK menu nutrition · choose a restaurant</div><div class="grid">'+restaurants.map(r=>`<button class="btn alt" data-r="${r.id}">${r.emoji} ${esc(r.name)}</button>`).join('')+'</div><div id="restaurantItems"></div>';body.querySelectorAll('[data-r]').forEach(b=>b.onclick=()=>renderItems(b.dataset.r))}
function renderItems(id){const r=restaurants.find(x=>x.id===id);if(!r)return;const wrap=$('restaurantItems');let basket=[];wrap.innerHTML='<input id="restaurantSearch" autocomplete="off" type="search" placeholder="🔍 Search '+esc(r.name)+' menu"><div id="restaurantResults"></div><div id="restaurantBasket"></div>';const search=$('restaurantSearch'),results=$('restaurantResults'),basketEl=$('restaurantBasket');const draw=()=>{const term=search.value.toLowerCase();const items=r.items.filter(x=>x.name.toLowerCase().includes(term));results.innerHTML='<div class="card"><div class="row"><b>'+r.emoji+' '+esc(r.name)+'</b><span class="sub">'+items.length+' items</span></div>'+items.map((x,i)=>`<div class="item row"><div><b>${esc(x.name)}</b><div class="sub">${x.kcal} kcal${x.protein!=null?' · '+x.protein+'g protein':''}${x.carbs!=null?' · '+x.carbs+'g carbs':''}${x.fat!=null?' · '+x.fat+'g fat':''}</div><div class="sub">UK menu · nutrition can change</div></div><button class="btn small" data-add="${i}">＋</button></div>`).join('')+'</div>';results.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>{basket.push(items[+b.dataset.add]);renderBasket()})};const renderBasket=()=>{if(!basket.length){basketEl.innerHTML='';return}const total=k=>basket.reduce((a,x)=>a+(Number(x[k])||0),0);basketEl.innerHTML=`<div class="card"><div class="row"><b>🛒 Your order</b><button class="btn alt small" id="clearOrder">Clear</button></div>${basket.map((x,i)=>`<div class="item row"><div><b>${esc(x.name)}</b><div class="sub">${x.kcal} kcal</div></div><button class="btn alt small" data-remove="${i}">×</button></div>`).join('')}<div class="row" style="margin-top:12px"><div><b>${Math.round(total('kcal'))} kcal</b><div class="sub">${Math.round(total('protein'))}g protein · ${Math.round(total('carbs'))}g carbs · ${Math.round(total('fat'))}g fat</div></div><button class="btn" id="addOrder">Add order</button></div></div>`;basketEl.querySelector('#clearOrder').onclick=()=>{basket=[];renderBasket()};basketEl.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{basket.splice(+b.dataset.remove,1);renderBasket()});basketEl.querySelector('#addOrder').onclick=()=>addOrder(r,basket)};search.addEventListener('input',draw);search.addEventListener('keydown',e=>e.stopPropagation());draw();search.focus()}
function addOrder(r,basket){if(!basket.length)return;let s={};try{s=JSON.parse(localStorage.getItem(KEY))||{}}catch(e){}s.logs=Array.isArray(s.logs)?s.logs:[];const d=new Date();const date=d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');const total=k=>basket.reduce((a,x)=>a+(Number(x[k])||0),0);s.logs.push({date,name:r.name+' — '+basket.map(x=>x.name).join(', '),kcal:total('kcal'),protein:total('protein'),carbs:total('carbs'),fat:total('fat'),source:'restaurant'});localStorage.setItem(KEY,JSON.stringify(s));window.location.reload()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount);else mount();setTimeout(mount,1000);setTimeout(mount,3000);
})();